version: "3.9"

services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"  # Maps host:container ports
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

  web-tests:
    image: full-stack-js-app-web  # ⚠️ This refers to an existing built image
    working_dir: /app               # Optional: set working directory
    command: ["npm", "test"]        # ✅ Specify how the tests should run
    volumes:
      - ./frontend:/app
    depends_on:
      - web  

  api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ./docker-entrypoint.sh
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - vidly:/data/db

volumes:
  vidly:
