version: "3.9"

services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"  # Maps host:container ports
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - vidly:/data/db

volumes:
  vidly:
